language: cpp

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
branches:
  only:
    - master
    - develop

# build with both gcc and clang to ensure compatibility
compiler:
  - gcc
  - clang

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libbz2-dev libncurses5-dev libmysqlclient-dev libreadline-dev libsdl1.2-dev libssl-dev zlib1g-dev libace-dev

script:
  - test -d _build || mkdir _build
  - test -d _install || mkdir _install
  - cd _build
  - cmake -DCMAKE_INSTALL_PREFIX=../_install -DCMAKE_BUILD_TYPE=Debug -DWITH_MOD_LUA=0 -DWITH_MOD_SCRIPTDEV2=1 ..
  - make -j4

